versions/appinfo/0.0.7.toml
Turn off app on both platforms on production to test runbook
=> Release 0.0.7

static/topics/studying-training
- Fixed title for student-finance
=> [GOVUKAPP-1078] Studying - training

static/topics/retiring-taking-pension
- Updated managing-your-pension title
=> [GOVUKAPP-1078] Retiring taking pension

static/topics/universal-credit
- Updated `help-with-childcare-costs` title
=> [GOVUKAPP-1078] Universal Credit

static/topics/tax-free-childcare
- Removed `managing-benefits` from subtopics
- Updated `help-with-childcare-costs` title
=> [GOVUKAPP-1078]  Tax-free childcare

static/topics/arranging-childcare
- Changed popular `help-with-childcare-costs` title
- Replaced unpopular `help-with-childcare-costs` with `help-with-childcare-costs/free-childcare-2-year-olds-claim-benefits`
=> [GOVUKAPP-1078] Arranging childcare

static/topics/bankruptcy-insolvency
- Remove staff-redundant from popular
- Add calculate-employee-redundancy to popular
=> [GOVUKAPP-1078]  Bankruptcy insolvency

static/topics/company-tax-returns
- Added dealing-with-HMRC subtopic
=> [GOVUKAPP-1078] Company tax returns

static/topics/support-for-families, static/topics/tax-free-childcare
- Updated Tax-Free childcare subtopic title
- Updated help-with-childcare-costs title
- Made check-eligible-free-childcare-if-youre-working popular
=> [GOVUKAPP-1078] Tax free childcare updates

static/topics/child-benefit
- Added managing-benefits to subtopics
- Made report-changes-child-benefit popular
=> [GOVUKAPP-1078] Updated child-benefit content

static/topics/benefits
Added new benefits content according to: https://govukverify.atlassian.net/browse/GOVUKAPP-1078
=> [GOVUKAPP-1078] - Added new benefits step-by-step content

static/topics/visas-study-in-uk
- Added student-sponsor-loses-licence
=> [GOVUKAPP-1078] Visas to study in the UK

static/topics/student-finance, static/topics/student-funding-if-eligible
- Removed popular content
- Updated `student-funding-if-eligible` title
=> [GOVUKAPP-1078] Student Finance

static/topics/business
- Removed self-assessment-tax-returns from business
=> [GOVUKAPP-1078] Business updates

static/topics/benefits
Reverts alphagov/govuk-mobile-backend-config#48
=> Revert "Fixed smart apostrophes in benefits"

package-lock.json, versions/appinfo/0.0.8.toml
[JIRA Ticket](https://govukverify.atlassian.net/browse/GOVUKAPP-1404)
=> GOVUKAPP-1404 : Add `local` feature flag

.github/workflows/deploy-integration.yaml
Useful for testing before merging into main.
=> Add workflow dispatch to integration

versions/appinfo/0.0.9.toml
Currently, localServices is added to the default config which is only used in integration. This blocks config for production, without removing it first also adds a risk of deploying the test config to production, accidentally.
Used https://jsondiff.com/ to compare diffs which look correct. See below for links / output.
Integration config: 
* https://app.integration.publishing.service.gov.uk/config/appinfo/ios
* https://app.integration.publishing.service.gov.uk/config/appinfo/android
Production config: 
* https://app.publishing.service.gov.uk/config/appinfo/ios
* https://app.publishing.service.gov.uk/config/appinfo/android
Output of generating the config file:
```
$ npm start generate versions/appinfo/0.0.9.toml
> govuk-mobile-backend-config@0.0.1 prestart
> npm run compile
> …
```
=> Utilises env specific objects

static/topics/support-health-condition-disability, static/topics/travel-abroad
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-1237)
=> GOVUKAPP-1237 Topic content changes

versions/appinfo/0.0.13.toml
New flag for enabling chat opt-in flow
=> Add chat opt in feature flag

versions/appinfo/0.0.16.toml
Add an emergency alert to default so appears in int and prod.
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-2381)
=> GOVUKAPP_2381 Emergency alert as default

versions/appinfo/0.0.21.toml
- Removed alert banner 
- Move userFeedbackBanner to integration only
=> [GOVUKAPP-2492] - Emergency Alert Banner (Remove)

static/topics/child-benefit, static/topics/corporation-tax, static/topics/dealing-with-debt, static/topics/doing-postgraduate-course, static/topics/doing-undergraduate-course, static/topics/employing-people, static/topics/income-tax, static/topics/national-insurance, static/topics/savings-accounts-children, static/topics/support-housing-living-costs, static/topics/tax-credits, static/topics/tax-free-childcare, static/topics/vat
Updates to topics and subtopics to keep them up to date, as per this ticket https://govukverify.atlassian.net/jira/software/c/projects/GOVUKAPP/boards/617?selectedIssue=GOVUKAPP-2509
=> Topics updates, September 2025

versions/appinfo/0.0.23.toml
Add an ID to dismissible chat banner
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-2493)
=> GOVUKAPP-2493 Add chat banner id

versions/appinfo/0.0.24.toml
Add new refresh token expiry seconds property
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-2586)
=> GOVUKAPP-2586 Refresh token expiry seconds
